sudo: false
language: python
python:
  - "3.5"
install: pip install -r requirements.txt
script: py.test
notifications:
  email:
    recipients:
      - code@opendataservices.coop
    on_success: never # default: change
    on_failure: always # default: always
