sudo: false
language: python
python:
  - "3.5"
jobs:
  include:
    - stage: test
      install: pip install -r requirements.txt
      script: py.test
    - stage: test
      install: gem install gist
      script: travis_wait 30 ./test_datagetter.sh
sudo: false
notifications:
  email:
    recipients:
      - ben.webb@opendataservices.coop
    on_success: never # default: change
    on_failure: always # default: always
